import { AnimatePresence, motion } from 'framer-motion'
import { ChevronLeft, ChevronRight, X } from 'lucide-react'
import { useEffect } from 'react'
import type { Project } from '../data/projects'

export function FullscreenMediaViewer({ item, items, onClose, onNavigate }: { item: Project | null; items: Project[]; onClose: () => void; onNavigate: (item: Project) => void }) {
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); const index = item ? items.findIndex((p) => p.id === item.id) : -1; if (event.key === 'ArrowRight' && items[index + 1]) onNavigate(items[index + 1]); if (event.key === 'ArrowLeft' && items[index - 1]) onNavigate(items[index - 1]); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [item, items, onClose, onNavigate])
  useEffect(() => { document.body.style.overflow = item ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [item])
  const index = item ? items.findIndex((p) => p.id === item.id) : -1
  return <AnimatePresence>{item && <motion.div className="fixed inset-0 z-50 grid place-items-center bg-[#050505]/95 p-4 backdrop-blur-xl" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} role="dialog" aria-modal="true"><motion.div className="relative flex h-full w-full items-center justify-center" initial={{ scale: .96 }} animate={{ scale: 1 }} exit={{ scale: .96 }} onClick={(e) => e.stopPropagation()}>{item.type === 'video' ? <video key={item.id} src={item.src} poster={item.thumbnail} autoPlay controls muted loop playsInline className="max-h-full max-w-full rounded-2xl object-contain" /> : <img key={item.id} src={item.src} alt={item.title} className="max-h-full max-w-full rounded-2xl object-contain" />}<button onClick={onClose} aria-label="Close" className="absolute right-0 top-0 grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-black/30"><X size={19}/></button>{index > 0 && <button onClick={() => onNavigate(items[index - 1])} aria-label="Previous" className="absolute left-0 grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-black/30"><ChevronLeft /></button>}{index < items.length - 1 && <button onClick={() => onNavigate(items[index + 1])} aria-label="Next" className="absolute right-0 grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-black/30"><ChevronRight /></button>}<span className="absolute bottom-1 left-1/2 -translate-x-1/2 text-[10px] uppercase tracking-[.18em]">{item.title}</span></motion.div></motion.div>}</AnimatePresence>
}
